--- #YAML:1.0
name: Acme-JavaTrace
version: 0.05
author:
  - |-
    Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Module for using Java-like stack traces
license: perl
requires:
  Data::Dumper: 0
provides:
  Acme::JavaTrace:
    file: lib/Acme/JavaTrace.pm
    version: 0.05
generated_by: Module::Build version 0.2611
