--- #YAML:1.0
name: Acme-JavaTrace
version: 0.01
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Acme::JavaTrace:
    file: lib/Acme/JavaTrace.pm
    version: 0.01
generated_by: Module::Build version 0.19_05
